server:
  port: ${GPC_FACADE_SERVER_PORT:8086}
  ssl:
    enabled: ${SSL_ENABLED:false}
    protocol: TLS
    enabled-protocols: TLSv1.2
    key-store: ${KEY_STORE:classpath:certs/keystore.jks}
    key-password: ${KEY_PASSWORD}
    key-store-password: ${KEY_STORE_PASSWORD}
    trust-store: ${TRUST_STORE:classpath:certs/truststore.jks}
    trust-store-password: ${TRUST_STORE_PASSWORD}
    client-auth: need

logging:
  level:
    uk.nhs.adaptors.pss.gpc: ${PS_LOGGING_LEVEL:INFO}

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: ${PS_DB_URL:jdbc:postgresql://localhost:5432/patient_switching}
    username: postgres
    password: ${GPC_FACADE_USER_DB_PASSWORD:1234}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings

amqp:
  pss:
    queueName: ${PS_QUEUE_NAME:pssQueue}
    broker: ${PS_AMQP_BROKER:amqp://localhost:5672}
    username: ${PS_AMQP_USERNAME:guest}
    password: ${PS_AMQP_PASSWORD:guest}
    maxRedeliveries: ${PS_AMQP_MAX_REDELIVERIES:3}
